#### general settings
name: 002_EDVR_predeblur_EDVRwoTSAIni_lr1e-4_600k_LicensePlate_LrCAR4S_fixTSA50k
use_tb_logger: true
model: VideoSR_base
distortion: sr
scale: 4
gpu_ids: [0]

#### datasets
datasets:
  train:
    name: licensePlate
    mode: licensePlate
    interval_list: [1]
    random_reverse: false
    border_mode: false
    dataroot_GT: /workspace/video_sr/EDVR/datasets/license_plate/license_plate.lmdb
    dataroot_LQ: /workspace/video_sr/EDVR/datasets/license_plate/license_plate_bicubic_blur_x4.lmdb
    cache_keys: LicensePlate_trainval_keys.pkl

    N_frames: 5
    use_shuffle: true
    n_workers: 4  # per GPU
    batch_size: 4
    GT_size: 256
    LQ_size: 64
    use_flip: true
    use_rot: true
    color: RGB

#### network structures
network_G:
  which_model_G: EDVR
  nf: 128
  nframes: 5
  groups: 8
  front_RBs: 5
  back_RBs: 40
  predeblur: true
  HR_in: false
  w_TSA: true

#### path
path:
  pretrain_model_G: ../experiments/pretrained_models/EDVR_REDS_SRblur_L.pth
  strict_load: false
  resume_state: ~

#### training settings: learning rate scheme, loss
train:
  lr_G: !!float 1e-4
  lr_scheme: CosineAnnealingLR_Restart
  beta1: 0.9
  beta2: 0.99
  niter: 600000
  ft_tsa_only: 50000
  warmup_iter: -1  # -1: no warm up
  T_period: [50000, 100000, 150000, 150000, 150000]
  restarts: [50000, 150000, 300000, 450000]
  restart_weights: [1, 1, 1, 1]
  eta_min: !!float 1e-7

  pixel_criterion: cb
  pixel_weight: 1.0
  val_freq: !!float 2e3

  manual_seed: 0

#### logger
logger:
  print_freq: 100
  save_checkpoint_freq: !!float 2e3
